services:
  # 1. PostgreSQL Database
  - name: stocksDB
    type: db
    databaseName: stocksdb
    db: postgres
    postgresMajorVersion: 13

  # 2. FastAPI Web Service
  - name: stocks-api
    type: web
    env: python
    buildCommand: "pip install -r requirement.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app"
    healthCheckPath: "/"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stocksDB
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9
      - key: API_KEY
        sync: false # Do not sync from Render's dashboard
      - key: FINNHUB_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY1
        sync: false

  # 3. Cron Job for Daily Data Fetching
  - name: daily-fetch
    type: cron
    env: python
    schedule: "0 4 * * *" # Run every day at 4:00 AM UTC
    buildCommand: "pip install -r requirement.txt"
    startCommand: "python -m api.tasks --task all"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stocksDB
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9
      - key: API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY1
        sync: false
